# Generated by Django 4.0.4 on 2022-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_answer_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='choice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
