# Generated by Django 5.1.6 on 2025-03-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_registration_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Address',
            field=models.CharField(max_length=15),
        ),
    ]
